services:
  # ───────────── Postgres (optional now, needed later) ─────────────
  db:
    image: postgres:16
    container_name: aiins_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  # ───────────── FastAPI backend ─────────────
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aiins_backend
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    # comment this block if you want to ignore db for now
    depends_on:
      db:
        condition: service_healthy

  # ───────────── React (Vite) frontend ─────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aiins_frontend
    env_file: .env
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - backend

volumes:
  pgdata:
